<a href="https://colab.research.google.com/github/PeHaash/CRSA-0.3/blob/main/notebooks/phase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Phase 1

Goal: to make a notebook that can handle these two Objectives:
  - No overlap in whitespaces
  - Use all free spaces


In [ ]:
## Constants of the Code:
SharedLib = "SharedLib.ph"
NumberOfObjetives = 2

# Initialization & Compile



In [ ]:
# @title InitializationSetup definition { form-width: "30%" }
# @markdown folder setup happens here: a class definition to use linux commands to make code ready to execute
# Folder Setup:
class InitializationSetup:
  def __init__(self, account_name: str, project_name: str, public_token: str):
    self.AccountName = account_name
    self.ProjectName = project_name
    self.PublicToken = public_token

  def removeSamples(self):
    # to delete the samples, we do not need them
    !rm -rf sample_data/ && echo "sample_data folder removed"

  def cloneGithub(self):
    !git clone https://{self.PublicToken}@github.com/{self.AccountName}/{self.ProjectName}.git && echo ">>CLONE IS DONE<<"

  def removeGitClone(self):
    # maybe we needed to delete git folder too, but we can just disconnect and delete timeline from runtime menu
    !rm -rf {self.ProjectName} && echo "git clone folder removed"

  def moveGitCodesToHomeDirectory(self):
    # moving important stuff into the home directory (except git files)
    !cp -r {self.ProjectName}/* ./ && echo "folders moved to the root" || echo "nah, it didn't work"

  def AssertThereIsObjFolder(self):
    # make obj folder if it not exists:
    !mkdir -p obj && echo "obj folder exists now"



In [ ]:
# @title InitializationSetup exectution
# public token will be expired on Mar 10 2024
groomer = InitializationSetup(account_name="PeHaash",
                              project_name="CRSA-0.3",
                              public_token=\
                              "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")

groomer.removeSamples()
groomer.cloneGithub()
groomer.moveGitCodesToHomeDirectory()
groomer.removeGitClone()
groomer.AssertThereIsObjFolder()


sample_data folder removed
Cloning into 'CRSA-0.3'...
remote: Enumerating objects: 348, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 348 (delta 46), reused 41 (delta 22), pack-reused 278
Receiving objects: 100% (348/348), 48.61 KiB | 1.87 MiB/s, done.
Resolving deltas: 100% (222/222), done.
>>CLONE IS DONE<<
folders moved to the root
git clone folder removed
obj folder exists now


In [ ]:
# @title Compile Functions { form-width: "30%" }
# @markdown CMake of the less-fortunate areas
FlagsOfCppCompile = "-std=c++20 -Wall -Wpedantic -fPIC -I ./ -I ./include -c -O2"
FlagsOfCppLinking = "-shared -fPIC -O2 -flto"


def Compile(file_name: str):
  !g++ src/{file_name}.cpp {FlagsOfCppCompile} -o obj/{file_name}.o && echo "{file_name} compilation done"

def Link(file_names: list[str]):
  line = " ".join([f"obj/{a}.o" for a in file_names])
  !g++ {line} {FlagsOfCppLinking} -o {SharedLib} && echo "Linking done"


In [ ]:
#@title Compiling Codes
SourceFiles = ["DisjointSet", "DualGridImplementation", "Wrapper"]
for Source in SourceFiles:
  Compile(Source)
Link(SourceFiles)


DisjointSet compilation done
DualGridImplementation compilation done
Wrapper compilation done
Linking done


# Wrapper

In [ ]:
#@title Imports
import ctypes
import numpy as np

In [ ]:
#@title struct definitions of C Shared Arrays

class CSA:
  # f32 = ctypes.POINTER(ctypes.c_float)
  # i32 = ctypes.POINTER(ctypes.c_int32)
  d64 = np.ctypeslib.ndpointer(dtype=np.float64, ndim=1, flags = 'C_CONTIGUOUS')
  # d64 = ctypes.POINTER(ctypes.c_double)
  c08 =  np.ctypeslib.ndpointer(dtype=np.int8, ndim=1, flags = 'C_CONTIGUOUS')
  # c08 = ctypes.POINTER(ctypes.c_char)

# class CSA_Float32(ctypes.Structure):
#   _fields_ = [
#       ("size", ctypes.c_uint64),
#       ("data", CSA.f32) # float_pointer
#   ]

class CSA_Double64(ctypes.Structure):
  _fields_ = [
      ("size", ctypes.c_uint64),
      ("data", CSA.d64)
  ]

# class CSA_Int32(ctypes.Structure):
#   _fields_ = [
#       ("size", ctypes.c_uint64),
#       ("data", CSA.i32)
#   ]

class CSA_Char8(ctypes.Structure):
  _fields_ = [
      ("size", ctypes.c_uint64),
      ("data", CSA.c08)
  ]



In [ ]:
# @title Imports DGI definition

class Features(ctypes.Structure):
  _fields_ = [
      ("Width", ctypes.c_uint32),
      ("Height", ctypes.c_uint32),
      ("SizeOfGridByCM", ctypes.c_double),
      ("TrueNorth", ctypes.c_double),
      ("WhiteSubspacePerRoom", ctypes.c_uint32)
  ]

# extern "C"{
# 	void* c_MakeDGI(Features fet);
# 	// void c_SetFeature(void*, Features);
# 	int32_t c_ImplementAndEvaluate(
# 		void* DGI,
# 		CSA_Char8& InputGrid,
# 		CSA_Double64& WhiteSpace,
# 		CSA_Double64& ColoredSpace,
# 		CSA_Double64& WSError,
# 		CSA_Double64& CSError,
# 		CSA_Double64& Scores);
# 	int32_t c_ImplementAndExport(
# 		void* DGI,
# 		CSA_Char8& InputGrid,
# 		CSA_Double64& WhiteSpace,
# 		CSA_Double64& ColoredSpace,
# 		CSA_Double64& WSError,
# 		CSA_Double64& CSError,
# 		CSA_Double64& Scores,
# 		CSA_Char8& ExportGrid);
# 	int32_t c_DeleteDGI(void*);

# }

class DualGridImplementation:
  de_library = ctypes.CDLL(f"./{SharedLib}")
  # void* c_MakeDGI(Features fet);
  p_MakeDGI = de_library.c_MakeDGI
  p_MakeDGI.argtypes = [Features]
  p_MakeDGI.restype = ctypes.c_void_p ## void*

  # void c_SetFeature(void*, Features); not done yet

  # int32_t c_ImplementAndEvaluate(...);
  p_ImplementAndEvaluate = de_library.c_ImplementAndEvaluate
  p_ImplementAndEvaluate.argtypes = [ctypes.c_void_p,
                                     CSA_Char8, CSA_Double64, CSA_Double64,
                                     CSA_Double64, CSA_Double64, CSA_Double64]
  p_ImplementAndEvaluate.restype = ctypes.c_int32

  # int32_t c_ImplementAndExport(...);
  p_ImplementAndExport = de_library.c_ImplementAndExport
  p_ImplementAndExport.argtypes = [ctypes.c_void_p,
                                   CSA_Char8, CSA_Double64, CSA_Double64,
                                   CSA_Double64, CSA_Double64, CSA_Double64,
                                   CSA_Char8]
  p_ImplementAndExport.restype = ctypes.c_int32

  # int32_t c_DeleteDGI(void*);
  p_DeleteDGI = de_library.c_DeleteDGI
  p_DeleteDGI.argtypes = [ctypes.c_void_p]
  p_DeleteDGI.restype = ctypes.c_int32

  def __init__(self, fet: Features):
    self.de_object = ctypes.c_void_p(DualGridImplementation.p_MakeDGI(fet))
    self.InternalFeatures = fet;
    self.GridSize_np = ctypes.c_uint64(fet.Width * fet.Height)
    self.GridSize = fet.Width * fet.Height


# 	int32_t c_ImplementAndEvaluate(
# 		void* DGI,
# 		CSA_Char8& InputGrid,
# 		CSA_Double64& WhiteSpace,
# 		CSA_Double64& ColoredSpace,
# 		CSA_Double64& WSError,
# 		CSA_Double64& CSError,
# 		CSA_Double64& Scores);
#  Inp.ctypes.data_as(CSA.f32)

  def ImplementAndEvaluate(self, InputGrid: np.array, WhiteSpace: np.array, ColoredSpace: np.array):
    ## define outputs:
    _Scores =  np.full(NumberOfObjetives, -1, dtype = np.float64)
    _WsError = np.full(self.GridSize, 0, dtype = np.float64)
    _CsError = np.full(self.GridSize, 0, dtype = np.float64)
    ## marshal inputs
    input_grid = CSA_Char8(self.GridSize_np, InputGrid.ctypes.data_as(CSA.c08))
    white_spaces =   CSA_Double64(self.GridSize_np,   WhiteSpace.ctypes.data_as(CSA.d64))
    colored_spaces = CSA_Double64(self.GridSize_np, ColoredSpace.ctypes.data_as(CSA.d64))
    ## marshal outputs
    ws_error = CSA_Double64(self.GridSize_np, _WsError.ctypes.data_as(CSA.d64))
    cs_error = CSA_Double64(self.GridSize_np, _CsError.ctypes.data_as(CSA.d64))
    scores = CSA_Double64(NumberOfObjetives, _Scores.ctypes.data_as(CSA.d64))
    ## do the shit
    ff = DualGridImplementation.p_ImplementAndEvaluate(self.de_object,
                                                  input_grid, white_spaces, colored_spaces,
                                                  ws_error, cs_error, scores)
    return [ff, _Scores, _WsError, _CsError]


  def ImplementAndExport(self, InputGrid: np.array, WhiteSpace: np.array, ColoredSpace: np.array):
    ## define outputs:
    _Scores =  np.full(NumberOfObjetives, -1, dtype = np.float64)
    _WsError = np.full(self.GridSize, 0, dtype = np.float64)
    _CsError = np.full(self.GridSize, 0, dtype = np.float64)
    _Export  = np.full(self.GridSize, 0, dtype = np.int8)
    ## marshal inputs
    input_grid = CSA_Char8(self.GridSize_np, InputGrid.ctypes.data_as(CSA.c08))
    white_spaces =   CSA_Double64(self.GridSize_np,   WhiteSpace.ctypes.data_as(CSA.d64))
    colored_spaces = CSA_Double64(self.GridSize_np, ColoredSpace.ctypes.data_as(CSA.d64))
    ## marshal outputs
    ws_error = CSA_Double64(self.GridSize_np, _WsError.ctypes.data_as(CSA.d64))
    cs_error = CSA_Double64(self.GridSize_np, _CsError.ctypes.data_as(CSA.d64))
    export = CSA_Char8(self.GridSize_np, _Export.ctypes.data_as(CSA.c08))
    scores = CSA_Double64(NumberOfObjetives, _Scores.ctypes.data_as(CSA.d64))
    ## do the shit
    DualGridImplementation.p_ImplementAndExport(self.de_object,
                                                  input_grid, white_spaces, colored_spaces,
                                                  ws_error, cs_error, scores,
                                                  export)
    return [_Scores, _WsError, _CsError, _Export]


  def __del__(self):
    print("delete")
    DualGridImplementation.p_DeleteDGI(self.de_object)
    print("delete OK!")


./SharedLib.ph


In [ ]:
fet = Features(10, 10, 1.0, 1.57, 6)
a = DualGridImplementation(fet)
# a = DualGridImplementation(Features(5,5,1.0,1.54,1))

In [ ]:
InputGrid = np.full(100, ord('F'),dtype=np.int8)
WhiteSpace = np.random.rand(100)
ColoredSpace = np.random.rand(100)
S = a.ImplementAndEvaluate(InputGrid, WhiteSpace, ColoredSpace)
# a.MarshallingSize
S

[0,
 array([ 0., -1.]),
 array([2., 2., 3., 3., 3., 3., 3., 3., 3., 1., 2., 3., 4., 4., 4., 4., 4.,
        4., 4., 2., 3., 4., 5., 5., 5., 5., 5., 5., 5., 3., 3., 4., 5., 5.,
        5., 5., 5., 5., 5., 3., 3., 4., 5., 6., 6., 6., 6., 6., 5., 3., 3.,
        4., 5., 6., 6., 6., 6., 6., 5., 3., 3., 4., 5., 6., 6., 6., 6., 6.,
        5., 3., 3., 4., 5., 6., 6., 6., 6., 6., 5., 3., 2., 3., 4., 5., 5.,
        5., 5., 5., 4., 3., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]

# ANN